import { Secretaria } from "../secretaria/secretaria";

export const listaDeSecretarias: Secretaria[] = [
    {
        id: 1,
        nome: "Secretaria de Saúde",
        telefone: 123456789,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',  
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 2,
        nome: "Secretaria de Educação",
        telefone: 987654321,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 3,
        nome: "Secretaria de Obras",
        telefone: 456789123,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 4,
        nome: "Secretaria de Urbanismo",
        telefone: 321654987,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 5,
        nome: "Secretaria de Assistência Social",
        telefone: 654321789,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 6,
        nome: "Secretaria de Meio Ambiente",
        telefone: 789123456,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 7,
        nome: "Secretaria de Segurança Pública",
        telefone: 159753468,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 8,
        nome: "Secretaria de Cultura",
        telefone: 753159852,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 9,
        nome: "Secretaria de Esportes",
        telefone: 951753468,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
    {
        id: 10,
        nome: "Secretaria de Transporte",
        telefone: 147258369,
        encarregado: 'Maria Silva',
        email: 'dimiendrixmmiranda@gmail.com',
        imagem: "/wireframe.png",
        descricaoEncarregado: 'Maria Silva é graduada em Medicina pela Universidade Federal e possui mais de 15 anos de experiência na área da saúde pública. Desde 2019, ela atua como Secretária de Saúde da cidade, onde tem liderado diversas iniciativas voltadas para a melhoria da saúde da população. Sua gestão é marcada pela implementação de programas de prevenção de doenças, ampliação do acesso a serviços de saúde e fortalecimento da rede de atendimento. Além disso, Maria é uma defensora ativa da saúde mental e do bem-estar da comunidade, promovendo campanhas de conscientização e suporte psicológico. Com uma abordagem colaborativa, ela trabalha em estreita parceria com equipes médicas, profissionais de saúde e a comunidade para atender às necessidades de todos os cidadãos.',
    },
];