import Noticia from "../noticia/Noticia";

export const listaDeNoticias: Noticia[] = [
    {
        id: 1,
        titulo: "Prefeitura lança programa de arborização urbana",
        descricao: "O programa visa plantar 500 novas árvores em áreas urbanas de Joaquim Távora até o final do ano.",
        imagem: "/wireframe.png",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 2,
        titulo: "Feira de produtos locais acontece neste final de semana",
        descricao: "A tradicional feira contará com expositores de artesanato, alimentos orgânicos e música ao vivo.",
        imagem: "/wireframe.png",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 3,
        titulo: "Escola Municipal promove campeonato de xadrez",
        descricao: "O evento reuniu estudantes de diversas escolas da região para promover o aprendizado e a socialização.",
        imagem: "/wireframe.png",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 4,
        titulo: "Joaquim Távora comemora 95 anos de fundação",
        descricao: "Com desfiles e apresentações culturais, a cidade celebrou seu aniversário com grande participação da população.",
        imagem: "/wireframe.png",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 5,
        titulo: "Posto de saúde amplia horário de atendimento",
        descricao: "A unidade agora funciona até às 20h para atender melhor a população trabalhadora.",
        imagem: "/wireframe.png",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 6,
        titulo: "Caminhada ecológica reúne voluntários no Parque Municipal",
        descricao: "O evento contou com mais de 200 participantes para limpeza de trilhas e plantio de mudas.",
        imagem: "https://example.com/caminhada-ecologica.jpg",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 7,
        titulo: "Nova iluminação pública é instalada na Avenida Central",
        descricao: "Os novos postes de LED prometem maior eficiência energética e segurança para os moradores.",
        imagem: "https://example.com/iluminacao-publica.jpg",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 8,
        titulo: "Time de futebol local vence campeonato regional",
        descricao: "A equipe de Joaquim Távora conquistou o título após uma vitória emocionante nos pênaltis.",
        imagem: "https://example.com/time-campeao.jpg",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 9,
        titulo: "Biblioteca Municipal inaugura sala de leitura infantil",
        descricao: "O espaço foi pensado para incentivar a leitura entre crianças com atividades lúdicas e contação de histórias.",
        imagem: "https://example.com/sala-leitura.jpg",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    },
    {
        id: 10,
        titulo: "Evento cultural celebra diversidade musical da região",
        descricao: "O festival contou com apresentações de bandas locais e danças típicas que encantaram o público.",
        imagem: "https://example.com/evento-cultural.jpg",
        materia: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sagittis rhoncus iaculis. Proin a justo at magna efficitur sodales non ac metus. Quisque vitae augue diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla ultricies ex ipsum, ac sollicitudin tellus vestibulum sed. Mauris quis tortor tempus, bibendum turpis eget, egestas tellus. Etiam tempus luctus tellus, vitae commodo libero iaculis pellentesque. Aenean eget feugiat magna. Aliquam nec dolor lectus. Aenean dapibus sollicitudin neque, a accumsan massa malesuada vitae. Duis iaculis pretium dignissim. Nunc sed erat gravida, tempus nunc sit amet, vestibulum massa. Vivamus tempor leo in vehicula tempor. Duis tincidunt blandit massa a rutrum. Ut gravida dui elit, vitae tristique ex aliquet non. Fusce tortor augue, accumsan ac metus porttitor, varius convallis ante.',
            'In a rutrum purus, vel vulputate mauris. Maecenas at porttitor purus. Quisque feugiat nibh et nisl ultrices ultricies. Cras imperdiet blandit nibh, id scelerisque mauris euismod sit amet. Donec consectetur fringilla scelerisque. Etiam sagittis elementum sapien, eget tempus risus ullamcorper vitae. Pellentesque eu egestas massa, vitae tempor tellus. In tincidunt, lectus non convallis blandit, diam ipsum elementum ex, vel porttitor nisl elit a dolor. Phasellus lacinia tortor eget bibendum elementum. Proin vestibulum elit quis ex molestie interdum. Curabitur sed tristique dui, at fringilla eros. Aenean dignissim, turpis vel condimentum volutpat, eros magna congue lectus, vel scelerisque nulla elit nec nunc. Duis ac tortor sit amet diam imperdiet mattis facilisis dapibus nibh. Nulla facilisi.',
            'Mauris et iaculis ipsum, id fringilla ligula. Mauris consectetur pretium nulla, ut laoreet sem mollis sed. Nam eget orci nunc. Donec venenatis nec odio nec venenatis. Etiam elementum vel orci sit amet tempor. Nam elementum diam vel lectus faucibus, ultricies malesuada velit dapibus. Ut rutrum tortor id mi interdum posuere. Etiam porta iaculis odio. Nulla sed est id est pulvinar sodales at at risus.',
            'Donec efficitur faucibus nisl, pharetra venenatis turpis molestie ut. Fusce risus justo, eleifend eget lacus eget, tempus auctor tellus. Integer at ultricies sapien, quis fringilla magna. Nulla facilisi. Sed at sagittis enim. Fusce in urna nisl. Quisque in ante felis. In sit amet augue non nulla dapibus auctor sit amet eu metus. Aenean vulputate cursus ligula id auctor.'
        ]
    }
];