import { FaFacebookSquare, FaInstagramSquare, FaPhone } from "react-icons/fa";
import Comercio from "../comercio/Comercio";
import { IoLogoWhatsapp } from "react-icons/io5";
import { MdEmail } from "react-icons/md";

export const listaDeComercio: Comercio[] = [
    {
        id:1,
        latitude: -23.498257758382454,
        longitude: -49.924160190634396,
        icone: '/icones/escola.png',
        imagem: '/wireframe.png',
        texto: 'Padaria Pão Quente',
        atendimento: 'Seg-Sáb: 6h às 20h',
        telefone: '(11) 1234-5678',
        endereco: 'Rua das Flores, 123 - Centro',
        tipo: 'Padaria',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:2,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/hospital.png',
        imagem: '/wireframe.png',
        texto: 'Restaurante Sabor Caseiro',
        atendimento: 'Seg-Dom: 11h às 15h',
        telefone: '(11) 8765-4321',
        endereco: 'Av. Principal, 456 - Jardim América',
        tipo: 'Restaurante',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:3,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Supermercado Econômico',
        atendimento: 'Seg-Dom: 8h às 22h',
        telefone: '(11) 1122-3344',
        endereco: 'Rua do Mercado, 789 - Vila Nova',
        tipo: 'Supermercado',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:4,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Supermercado Econômico',
        atendimento: 'Seg-Dom: 8h às 22h',
        telefone: '(11) 1122-3344',
        endereco: 'Rua do Mercado, 789 - Vila Nova',
        tipo: 'Supermercado',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:5,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Padaria Delícia',
        atendimento: 'Seg-Sáb: 6h às 20h',
        telefone: '(11) 3344-5566',
        endereco: 'Rua Pão Quente, 45 - Centro',
        tipo: 'Padaria',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:6,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Restaurante Bom Sabor',
        atendimento: 'Ter-Dom: 11h às 15h',
        telefone: '(11) 6677-8899',
        endereco: 'Av. Principal, 1234 - Jardim América',
        tipo: 'Restaurante',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:7,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Farmácia Saúde',
        atendimento: 'Seg-Sex: 8h às 20h',
        telefone: '(11) 4455-6677',
        endereco: 'Rua da Saúde, 789 - Bairro Novo',
        tipo: 'Farmacia',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:8,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Pet Shop Amigos',
        atendimento: 'Seg-Sáb: 9h às 18h',
        telefone: '(11) 9988-7766',
        endereco: 'Av. dos Animais, 456 - Centro',
        tipo: 'PetShop',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:9,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Academia Fitness Life',
        atendimento: 'Seg-Sex: 6h às 22h',
        telefone: '(11) 5566-7788',
        endereco: 'Rua do Movimento, 101 - Centro',
        tipo: 'Academia',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:10,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Livraria Saber',
        atendimento: 'Seg-Sáb: 9h às 19h',
        telefone: '(11) 7788-9900',
        endereco: 'Av. do Conhecimento, 234 - Centro',
        tipo: 'Livraria',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
    {
        id:11,
        latitude: -23.498890871745232, 
        longitude: -49.926367842532585,
        icone: '/icones/posto-de-saude.png',
        imagem: '/wireframe.png',
        texto: 'Mercadinho Popular',
        atendimento: 'Seg-Dom: 7h às 22h',
        telefone: '(11) 2233-4455',
        endereco: 'Rua dos Alimentos, 567 - Bairro Alto',
        tipo: 'Supermercado',
        redesSociais: [
            { icone: <FaPhone />, link: '/', nome: 'Telefone' },
            { icone: <MdEmail />, link: '/', nome: 'Email' },
            { icone: <FaInstagramSquare />, link: '/', nome: 'Instagram' },
            { icone: <FaFacebookSquare />, link: '/', nome: 'Facebook' },
            { icone: <IoLogoWhatsapp />, link: '/', nome: 'WhatsApp' },
        ],
    },
]