export default function traduzirCondicao(condicao: string): string {
    const traducoes: Record<string, string> = {
        'Sunny': 'Ensolarado',
        'Clear': 'Limpo',
        'Partly cloudy': 'Parcialmente nublado',
        'Cloudy': 'Nublado',
        'Overcast': 'Encoberto',
        'Mist': 'Névoa',
        'Patchy rain possible': 'Possibilidade de chuva esparsa',
        'Patchy snow possible': 'Possibilidade de neve esparsa',
        'Patchy sleet possible': 'Possibilidade de granizo esparso',
        'Patchy freezing drizzle possible': 'Possibilidade de garoa congelante esparsa',
        'Thundery outbreaks possible': 'Possibilidade de trovoadas',
        'Blowing snow': 'Nevasca',
        'Blizzard': 'Nevasca forte',
        'Fog': 'Nevoeiro',
        'Freezing fog': 'Nevoeiro congelante',
        'Patchy light drizzle': 'Garoa leve esparsa',
        'Light drizzle': 'Garoa leve',
        'Freezing drizzle': 'Garoa congelante',
        'Heavy freezing drizzle': 'Garoa congelante forte',
        'Patchy light rain': 'Chuva leve esparsa',
        'Light rain': 'Chuva leve',
        'Moderate rain at times': 'Chuva moderada intermitente',
        'Moderate rain': 'Chuva moderada',
        'Heavy rain at times': 'Chuva forte intermitente',
        'Heavy rain': 'Chuva forte',
        'Light freezing rain': 'Chuva congelante leve',
        'Moderate or heavy freezing rain': 'Chuva congelante moderada ou forte',
        'Light sleet': 'Granizo leve',
        'Moderate or heavy sleet': 'Granizo moderado ou forte',
        'Patchy light snow': 'Neve leve esparsa',
        'Light snow': 'Neve leve',
        'Patchy moderate snow': 'Neve moderada esparsa',
        'Moderate snow': 'Neve moderada',
        'Patchy heavy snow': 'Neve forte esparsa',
        'Heavy snow': 'Neve forte',
        'Ice pellets': 'Pelotas de gelo',
        'Light rain shower': 'Pancada de chuva leve',
        'Moderate or heavy rain shower': 'Pancada de chuva moderada ou forte',
        'Torrential rain shower': 'Pancada de chuva torrencial',
        'Light sleet showers': 'Pancada de granizo leve',
        'Moderate or heavy sleet showers': 'Pancada de granizo moderada ou forte',
        'Light snow showers': 'Pancada de neve leve',
        'Moderate or heavy snow showers': 'Pancada de neve moderada ou forte',
        'Patchy light rain with thunder': 'Chuva leve esparsa com trovoadas',
        'Moderate or heavy rain with thunder': 'Chuva moderada ou forte com trovoadas',
        'Patchy light snow with thunder': 'Neve leve esparsa com trovoadas',
    };

    return traducoes[condicao] || 'Condição desconhecida';
}
